import os

#####################################
##### Projeto Escola - Versão 4 #####
#####################################

op_princ = ''
while op_princ != '0':
    os.system('clear')
    print("############################################")
    print("######       Projeto SIG-Escola       ######")
    print("############################################")
    print("#####      1 - Módulo Aluno            #####")
    print("#####      2 - Módulo Professor        #####")
    print("#####      3 - Módulo Turma            #####")
    print("#####      4 - Módulo Relatório        #####")
    print("#####      5 - Módulo Informações      #####")
    print("#####      0 - Sair                    #####")
    op_princ = input("##### Escolha sua opção: ")

    if op_princ == '1':
        op_aluno = ''
        while op_aluno != '0':
            os.system('clear')
            print()
            print("############################################")
            print("#####           Módulo Aluno           #####")
            print("############################################")
            print("##### 1 - Cadastrar Aluno              #####")
            print("##### 2 - Exibir Dados do Aluno        #####")
            print("##### 3 - Alterar Dados do Aluno       #####")
            print("##### 4 - Excluir Aluno                #####")
            print("##### 0 - Retornar ao Menu Principal   #####")
            op_aluno = input("##### Escolha sua opção: ")
            print()
            if op_aluno == '1':
                os.system('clear')
                print()
                print("############################################")
                print("#####           Cadastra Aluno         #####")
                print("############################################")
                print()
                nome = input("##### Nome: ")
                print()
                matr = input("##### Matrícula: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Aluno cadastrado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_aluno == '2':
                os.system('clear')
                print()
                print("############################################")
                print("#####        Exibe Dados do Aluno      #####")
                print("############################################")
                print()
                print("##### Nome: ", nome)
                print("##### Matrícula: ", matr)
                print("##### Email: ", email)
                print("##### Celular: ", fone)
                print()
                input("Tecle <ENTER> para continuar...")
            elif op_aluno == '3':
                os.system('clear')
                print()
                print("############################################")
                print("#####       Altera Dados do Aluno      #####")
                print("############################################")
                print()
                nome = input("##### Nome: ")
                print()
                matr = input("##### Matrícula: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Aluno alterado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_aluno == '4':
                os.system('clear')
                print()
                print("############################################")
                print("#####         Exclui Aluno             #####")
                print("############################################")
                print()
                matr = input("##### Matrícula: ")
                print()
                print("Aluno excluído com sucesso!")
                input("Tecle <ENTER> para continuar...")
    elif op_princ == '2':
        op_prof = ''
        while op_prof != '0':
            os.system('clear')
            print()
            print("############################################")
            print("#####         Módulo Professor         #####")
            print("############################################")
            print("##### 1 - Cadastrar Professor          #####")
            print("##### 2 - Exibir Dados do Professor    #####")
            print("##### 3 - Alterar Dados do Professor   #####")
            print("##### 4 - Excluir Professor            #####")
            print("##### 0 - Retornar ao Menu Principal   #####")
            op_prof = input("##### Escolha sua opção: ")
            print()
            if op_prof == '1':
                os.system('clear')
                print()
                print("############################################")
                print("#####         Cadastra Professor       #####")
                print("############################################")
                print()
                nome = input("##### Nome: ")
                print()
                cpf = input("##### CPF: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Professor cadastrado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_prof == '2':
                os.system('clear')
                print()
                print("############################################")
                print("#####      Exibe Dados do Professor    #####")
                print("############################################")
                print()
                print("##### Nome: ", nome)
                print("##### CPF: ", cpf)
                print("##### Email: ", email)
                print("##### Celular: ", fone)
                print()
                input("Tecle <ENTER> para continuar...")
            elif op_prof == '3':
                os.system('clear')
                print()
                print("############################################")
                print("#####     Altera Dados do Professor    #####")
                print("############################################")
                print()
                nome = input("##### Nome: ")
                print()
                cpf = input("##### CPF: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Professor alterado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_prof == '4':
                os.system('clear')
                print()
                print("############################################")
                print("#####       Exclui Professor           #####")
                print("############################################")
                print()
                cpf = input("##### CPF: ")
                print()
                print("Professor excluído com sucesso!")
                input("Tecle <ENTER> para continuar...")
    elif op_princ == '3':
        op_turma = ''
        while op_turma != '0':
            os.system('clear')
            print()
            print("############################################")
            print("#####           Módulo Turma           #####")
            print("############################################")
            print("##### 1 - Cadastrar Turma              #####")
            print("##### 2 - Exibir Dados da Turma        #####")
            print("##### 3 - Alterar Dados da Turma       #####")
            print("##### 4 - Excluir Turma                #####")
            print("##### 0 - Retornar ao Menu Principal   #####")
            op_turma = input("##### Escolha sua opção: ")
            print()
            if op_turma == '1':
                os.system('clear')
                print()
                print("############################################")
                print("#####           Cadastra Turma         #####")
                print("############################################")
                print()
                nome_turma = input("##### Nome da Turma: ")
                print()
                cod_turma = input("##### Código da Turma: ")
                print()
                horario = input("##### Horário das Aulas: ")
                print()
                cpf_prof = input("##### CPF do Professor: ")
                print()
                print("Professor cadastrado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_turma == '2':
                os.system('clear')
                print()
                print("############################################")
                print("#####        Exibe Dados da Turma      #####")
                print("############################################")
                print()
                print("##### Código da Turma: ", cod_turma)
                print("##### Nome da Turma: ", nome_turma)
                print("##### Horário: ", horario)
                print("##### Professor: ", cpf_prof)
                print()
                input("Tecle <ENTER> para continuar...")
            elif op_turma == '3':
                os.system('clear')
                print()
                print("############################################")
                print("#####       Altera Dados da Turma      #####")
                print("############################################")
                print()
                nome_turma = input("##### Nome da Turma: ")
                print()
                cod_turma = input("##### Código da Turma: ")
                print()
                horario = input("##### Horário das Aulas: ")
                print()
                cpf_prof = input("##### CPF do Professor: ")
                print()
                print("Turma alterada com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_turma == '4':
                os.system('clear')
                print()
                print("############################################")
                print("#####         Exclui Turma             #####")
                print("############################################")
                print()
                cod_turma = input("##### Código da Turma: ")
                print()
                print("Turma excluída com sucesso!")
                input("Tecle <ENTER> para continuar...")
    elif op_princ == '4':
        print()
        print("############################################")
        print("#####         Módulo Relatório         #####")
        print("############################################")
        print("##### 1 - Lista Geral de Alunos        #####")
        print("##### 2 - Lista Geral de Professores   #####")
        print("##### 3 - Lista Geral de Turmas        #####")
        print("##### 4 - Lista de Alunos por Turma    #####")
        print("##### 5 - Lista de Turmas p/ Professor #####")
        print("##### 0 - Retornar ao Menu Principal   #####")
        op_aluno = input("##### Escolha sua opção: ")
        print()
        input("Tecle <ENTER> para continuar...")
    elif op_princ == '5':
        print()
        print("############################################")
        print("#####  Você está no Módulo Informações  ####")
        print("############################################")
        print()
        print("##### Projeto de Gestão de uma Escola   ####")
        print("##### Equipe de desenvolvimento:        ####")
        print("##### Flavius Gorgônio @flgorgonio      ####")
        print("##### © Copyright by UFRN, since 2023   ####")
        print("##### Licença Pública Geral GNU         ####")
        print("##### www.gnu.org/licenses/gpl.html     ####")
        print()
        input("Tecle <ENTER> para continuar...")


print("Você encerrou o programa!")
print("Até logo!")
